version: '3.8'
name: product-crud
services:
  api:
    container_name: product-api
    image: products-crud-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 80:80
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db
volumes:
  postgres-data:
